### ISSUE TITLE
Issue with searchFairsharingRecords facetings

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/FAIRsharing-API#117]
`{searchFairsharingRecords(subjects:"bioinformatics" ){ aggregations currentPage perPage totalCount totalPages firstPage records{id type name abbreviation registry domains{ label}subjects{ label}taxonomies{ label}recordAssociations{ linkedRecord{name id registry } recordAssocLabel}status isRecommended }}}`
=> Should return more than 1 result (one returns proBed)

**Comment by knirirr** [comment]
How many results do you think it should return?

**Comment by terazus** [comment]
There's actually two issues:
1. proDeb isn't even tagged with Bioinformatics in its subjects so it shouldn't be returned
2. According to the current system it should return 36 results: https://fairsharing.org/standards/?selected_facets=expanded_onto_disciplines_exact:Bioinformatics

**Comment by terazus** [comment]
Or maybe even more than that If i extend to all records: (92 hits):
https://fairsharing.org/search/?q=&content=standard&content=biodbcore&content=policy&content=collection&name=&taxonomies=&organisations=&shortname=&description=&supportlinks=&licenses=&countries=&maintainers=&expanded_onto_domains=&expanded_onto_disciplines=Bioinformatics&user_defined_tags=&record_id=&miriam_id=&search_state=visible

**Comment by knirirr** [comment]
Thanks. Having taken a look I think that the search is working correctly, but the way the expanded names field has been generated means that it doesn't contain all the necessary names and so the results will be dodgy. This could be worked around by changing the indexing or the way the field is populated - I'll try the former in a moment.

proDeb is tagged with a child term of bioinformatics (Proteogenomics) and so will show up in a search - this is expected behaviour.

**Comment by terazus** [comment]
Rx !
