### ISSUE TITLE
Ontologised tag update

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-API#68]
There's a discussion on the legacy code repository relating to what are referred to here as Domains and Subjects:

https://github.com/ISA-tools/biosharing/issues/1207#issuecomment-532749501

Based on that, I think they need to have their field names modified, based on this:

https://github.com/FAIRsharing/domain-ontology/blob/master/RequiredAnnotationProperties.txt

That would appear to suggest that they should have the following fields:

- label: A text field which is seen in the UI as the primary name of this tag. This appears to be listed as "display_name" at present, and could replace that field and "name".
- IRI, of course.
- synonyms: Any other name by which they're known. I don't know if this needs to be an array of strings, or a hash, so that the type of synonym (e.g. 'AgroPortal alternative term', 'FAIRsharing alternative term') is stored in the application. This latter arrangement might only be needed if users need to know where these synonyms come from. 
- Definition: Text, will be needed if this is to be shown in the UI. 
- expanded_names: Labels and synonyms of any parent terms in the hierarchy which will be used for the elasticsearch indexes. 

The following code creates Domains and Subjects via sparql queries:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/tasks/ontologies.rake

I think that in that script the SPARQL queries are simply excluding the 'FAIRsharing alternative term' from synoyms rather than:

> Any time there is a 'FAIRsharing alternative term' for any class,
> this alternative term should be used by the FAIRsharing code in
> preference to the rdfs:label. The rdfs:label should then be displayed
> as part of the synonyms list. 

...but I'm not certain of that. This is probably the relevant part, lines 210-221:

```
    display_names = drao.query($drao_display_name_query)
    display_names.each do |d|
      name = d.to_h[:display].to_s
      iri = d.to_h[:class].to_s
      index = domains.index { |x| x.iri == iri }
      begin
        domains[index].alternative_names << domains[index].display_name
        domains[index].display_name = name
      rescue
        puts "Got index #{index.inspect} for #{iri}"
      end
    end
```

...assuming that only Domains are affected by this requirement. If Subjects are also affected then further changes are necessary to the script to reflect that.

**Comment by allysonlister** [comment]
Thanks very much @knirirr - this is very thorough. After a read of your comment, these seem to be your outstanding curator questions:

> That would appear to suggest that they should have the following fields: [...]

I am happy if you wish to name the fields in the new model in the same way as the ontology has them named, but this is not required (from a curation standpoint) as long as you know which ontology fields map to which variable names in the new code.

> I don't know if this needs to be an array of strings, or a hash, so that the type of synonym (e.g. 'AgroPortal alternative term', 'FAIRsharing alternative term') is stored in the application. This latter arrangement might only be needed if users need to know where these synonyms come from.

This is exactly correct. I don't know if our users wish to know where the synonyms come from. I can't immediately think of a use case where they would need to know (can you @Drosophilic)? From my POV an array of strings is fine as we don't need to store which type of alternative term it is, but I would like Pete's thoughts on this to be absolutely sure.

> assuming that only Domains are affected by this requirement. If Subjects are also affected then further changes are necessary to the script to reflect that.

Because SRAO is virtually entirely manually edited, there is no need for 'FAIRsharing alternative term', as our preferred label can simply be put directly into the label itself. I've had a check just now of SRAO to be sure of this, and found 1 accidental usage of the annotation property 'FAIRsharing alternative term'. I will raise a low-priority ticket on the SRAO issue tracker for it now.

Therefore this particular issue is only related to domains / DRAO.

Thanks! Please let me know if there are any other questions relating to this that need answering as part of this ticket.

**Comment by knirirr** [comment]
Thanks. For names, I would rather that anything in the code matches terms that you will use, to avoid any confusion. To that end I'll modify the existing code. 

As it's only Domains that require special treatment of a FAIRsharing term then I'll need a separate SPARQL query for that. Here's the query which excludes FAIRsharing alternative terms; are you able to suggest one which would return only this term?

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/tasks/ontologies.rake#L57-L70

**Comment by allysonlister** [comment]
Good morning @knirirr - please take a look at https://github.com/FAIRsharing/domain-ontology/blob/master/development/sparql/synonyms-from-subterms.sparql

That sparql query will return all children of the alternative_term property EXCEPT
# 'FAIRsharing alternative term'. However, this will *not* return the values within alternative_term itself, which are also required to complete the list of synonyms. Therefore what you need is to retrieve the values you get from https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/tasks/ontologies.rake#L57-L70 and add them to the list generated from https://github.com/FAIRsharing/domain-ontology/blob/master/development/sparql/synonyms-from-subterms.sparql

I haven't investigated how to put this in a single sparql query - if that is important, let me know and I'll take a look at the sparql docs and let you know.

Thanks!

**Comment by allysonlister** [comment]
Seeing as we have found one or two issues / sources of confusion as to what the sparql commands are intended to do (in https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/tasks/ontologies.rake) I think some documentation is in order.

@knirirr please could you add some comments in the ontologies.rake document for each sparql query stating what you think the query should be doing? Then I'll check the comments. It will ensure that what the code is doing, what you think it's doing, and what I think it should be doing is all aligned.

Thanks!

**Comment by allysonlister** [comment]
Issues with the domains.json

* data_3113: This class should be in /domains, but is missing. Label should be "Biological sample annotation" from the FAIRsharing alternative term.
* When there is a FAIRsharing alternative term, the rdfs:label should be moved to the expanded_names unless it is a case-insensitive match with the FAIRsharing alternative term. This isn't happening, at least in the case of e.g. http://purl.obolibrary.org/obo/OBI_0600047 where the rdfs:label is 'sequencing assay' and the FAIRsharing alternative term is 'Sequencing'; here, 'sequencing assay' is missing from expanded_names

I'll just confirm for @knirirr if it is the $drao_label_query that finds the "FAIRsharing Alternative Term" - I need to do pickup shortly so that may happen later this evening. Thanks!

**Comment by knirirr** [comment]
data_3113 is missing because it's not returned by $classes_query, which is where the records are actually created. It is found by $drao_label_query, explaining why the index error occurs - it was never created in the first place. Moving the $drao_label_query block and creating anything missing at this stage should fix this.

**Comment by allysonlister** [comment]
data_3113 does have parent terms in the hierarchy. And in future, if we do add further IRIs to filter-labels.txt, they might well have parents and/or children so this needs to be taken into account.

This is why I added in all_classes_query, in case you needed a full list of classes to iterate over to get your parents/children from.

Could you usefully modify line 259: `classes = drao.query($classes_query)` to be  `classes = drao.query($all_classes_query)`? It wouldn't have the rdfs:label values but you could add them using code similar to lines 307-314 but using classes_query at that point..?

**Comment by allysonlister** [comment]
Additionally, taking a line of the debugging output as an example:

> Failed to create entity|http://purl.obolibrary.org/obo/BFO_0000001: {:iri=>["has already been taken"]}

This class has two identical labels (both are 'entity'). As described in RequiredAnnotationProperties.md, If the multiple rdfs:label values are identical, the code should choose only one. So, shouldn't such identical matches be weeded out before it gets to the checks used to generate the debugging output?

Thanks!

**Comment by knirirr** [comment]
> This class has two identical labels (both are 'entity'). As described in RequiredAnnotationProperties.md, If the multiple rdfs:label values are identical, the code should choose only one. So, shouldn't such identical matches be weeded out before it gets to the checks used to generate the debugging output?

The stage where the identical matches are weeded out is the same stage where the debugging output is generated (currently lines 274-281).

**Comment by allysonlister** [comment]
Ah OK - thanks. Would it be possible to only write to the debug output if the multiple labels are non identical? As a curator, I'm not interested unless the multiple labels are different.

**Comment by knirirr** [comment]
> Could you usefully modify line 259: classes = drao.query($classes_query) to be classes = drao.query($all_classes_query)? It wouldn't have the rdfs:label values but you could add them using code similar to lines 307-314 but using classes_query at that point..?

I don't see how that would work; the query which finds children is $child_query, which is being called around line 333. That seems not to detect any children for data_3113 at all. Do you know why that is?

> Would it be possible to only write to the debug output if the multiple labels are non identical? As a curator, I'm not interested unless the multiple labels are different.

Yes, I have now done it.

**Comment by allysonlister** [comment]
There are no children for data_3113 - only parents. It is my hypothesis that the reason that you're not getting anything in the parent/child hierarchy is that when you search for child terms of its parent ('resource metadata, http://edamontology.org/data_2337), you'll get nothing from child_query...

```rake
  # Given the input IRI, this sparql query returns the "IRI label" pairs that 
  # are listed in the ontology as direct subclasses of the input IRI.
  def child_query(iri)
    SPARQL.parse(%Q{
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT DISTINCT ?class ?label
      WHERE
      {
        ?class rdfs:subClassOf ?<#{iri}>.
        ?class rdfs:label ?label.
      }
    })
  end
```
...because there is no rdfs:label for data_3113. Because there is no label, the entire query doesn't match. The query above, in English, is "give me all children of (e.g. 'resource metadata') that *definitely* also have an rdfs:label."

Apologies for not catching this when I provided you with the sparql in the first place - this is a sneaky one! I suggest that a possible solution might be to create a second query (called e.g. child_without_label_query). Then you can run both queries over each class that you're iterating through, and therefore be sure to get all classes, whether or not they have an rdfs:label.

```rake
  # Given the input IRI, this sparql query returns the IRI of classes that 
  # are listed in the ontology as direct subclasses of the input IRI and which *do not*
  # have an rdfs:label.
  def child_without_label_query(iri)
    SPARQL.parse(%Q{
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      SELECT DISTINCT ?class
      WHERE
      {
        ?class rdfs:subClassOf ?<#{iri}>.
        FILTER NOT EXISTS {?class rdfs:label ?label}.
      }
    })
  end
```
I've tested the above code on the command line, and it works as expected.

BTW, might it be at line 306 where you need to store the label you're about to overwrite inside the expanded_name list (as long as it isn't a case insensitive match)?

Thanks!

**Comment by knirirr** [comment]
Thanks - I've added that query and modified the label code. This is now deployed on the pre-alpha test site for viewing.

**Comment by allysonlister** [comment]
At a first glance, this is looking really good. However, I'm not working today so I can't take a closer look. Will do so before Monday though - thanks very much! :)

**Comment by allysonlister** [comment]
I went to have a closer look and it seems that the older version of the domains is at https://svisa-git.eng.ox.ac.uk/domains ?

```json
{
id: 1018358610,
iri: "http://edamontology.org/data_3113",
definitions: [ ],
label: "Biological sample annotation",
synonyms: [ ],
expanded_names: [ ],
created_at: "2019-09-27T14:02:51.607Z",
updated_at: "2019-09-27T14:02:51.607Z",
model: "domain"
},
```

I'm sure that when I briefly looked on Friday, data_3113 had the full complement of parent terms in its expanded_names list.. Has something changed at this url?

**Comment by knirirr** [comment]
The OWL files are up to date. Here's what I see after running the script again.

```
{

    "id": 1018358610,
    "iri": "http://edamontology.org/data_3113",
    "definitions": [ ],
    "label": "Biological sample annotation",
    "synonyms": [ ],
    "expanded_names": [
        "Data",
        "Data set",
        "Datum",
        "Data record",
        "Report",
        "Document",
        "Resource metadata",
        "Provenance metadata",
        "entity",
        "continuant",
        "generically dependent continuant",
        "information content entity"
    ],
    "created_at": "2019-09-27T14:02:51.607Z",
    "updated_at": "2019-09-30T13:21:38.600Z",
    "model": "domain"
},
```

**Comment by allysonlister** [comment]
Yep, that's what I saw on Friday, and what I'm seeing now. No idea why what I saw yesterday didn't have the expanded_names! Anyhow, will just check a few more things and then will let you know when I'm done. Thanks!

**Comment by allysonlister** [comment]
In Domains:

Checks performed that are correct in https://svisa-git.eng.ox.ac.uk/domains:
* IRIs correctly match labels and other annotation
* expanded_names contains the parents and not the children of the class
* synonyms listed in the ontology file are successfully stored as synonyms in the json
* Classes without rdfs:labels are handled correctly (currently only data_3113)

I could only find one issue with the current json for domains.

**FAIRsharing alternative terms are not being put into the label field**
Examples: http://purl.obolibrary.org/obo/GO_0009536 and http://purl.obolibrary.org/obo/GO_0005634. Please note that the only difference btwn the labels and the FAIRsharing alternative term is the casing. 

GO_0009536 = rdfs:label is "plastid", and FAIRsharing alternative term is "Plastid" to ensure that all FAIRsharing domains conform to our naming conventions.

Other FAIRsharing alternative terms are being correctly used when they are not case-insensitive matches to the rdfs:label (e.g. http://purl.obolibrary.org/obo/ERO_0000478, where the FAIRsharing alternative term "Bioactivity" has been correctly stored as the label, and "bioactivity assay" as one of the synonyms). 

Therefore I think the situation is that the case-insensitive matching is happening at the point where you are checking to see if the FAIRsharing alternative term should be used, rather than at the point where you decide if the rdfs:label should be stored as a synonym. As the RequiredAnnotationProperties.md says "When it has been overridden, the rdfs:label should instead be displayed as part of the synonyms list, UNLESS the rdfs:label is a case-insensitive match to the 'FAIRsharing alternative term'.", I think we need to change the program logic a bit:

 ```
Is there a FAIRsharing alternative term?
 If yes, then is the rdfs:label is a case-insensitive match?
    If yes, then store the FAIRsharing alternative term in the label field
    If no, then store the rdfs:label as a synonym **and** store the FAIRsharing alternative term in the label field
 
``` 


I'll just take a look at subjects now. thanks!

**Comment by allysonlister** [comment]
In Subjects:

Checks performed that are correct in https://svisa-git.eng.ox.ac.uk/subjects:

* IRIs correctly match labels and other annotation
* Multiple asserted hierarchies (multiple parents, e.g. http://edamontology.org/topic_3397) are correctly dealt with in expanded_names
* expanded_names contains the parents and not the children of the class
* synonyms listed in the ontology file are successfully stored as synonyms in the json

Everything looks good for subjects. Thanks!

**Comment by Drosophilic** [comment]
Excellent work guys!!
